apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: app
        image: joseangel190/helloworld:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  namespace: helloworld
  annotations:
    cert-manager.io/issuer: "issuer"
  labels:
    app: helloworld
spec:
  ingressClassName: nginx
  rules:
  - host: app.joseguerrero.pro
    http:
      paths:
      - path: /helloworld
        pathType: Prefix
        backend:
          service:
            name: helloworld-service
            port:
              number: 8080
  tls:
  - hosts:
    - app.joseguerrero.pro
    secretName: helloworld-secret

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: helloworld
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jaguerrerohuayanay@gmail.com
    privateKeySecretRef:
      name: issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
            
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-hpa
  namespace: helloworld
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
