name: CI/CD App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn clean install package
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_SERVER }}/${{ github.event.repository.name }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_SERVER }}/${{ github.event.repository.name }}:${{ github.sha }}
      
