name: Security

on:
  pull_request:
    branches: 
     - main
     - security
  
jobs:
  analyze:
    name: Analyze Default
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: java-kotlin
          build-mode: none 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}"

  dependency-review:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: 'high'
          vulnerability-check: true

  trivy:
      name: Trivy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: '${{ secrets.ACR_SERVER }}/${{ github.event.repository.name }}:latest'
            format: 'sarif'
            output: 'trivy-results.sarif'
          env:
            TRIVY_USERNAME: ${{ secrets.ACR_USERNAME }}
            TRIVY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'
